import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CursorFollower from "@/components/CursorFollower";
import { SmoothCursor } from "@/components/ui/smooth-cursor";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Faham's Portfolio",
  description: "Generated by create next app",
  keywords:
    "iamfaham.me, faham portfolio, iamfaham, Syed Mohammed Faham, Faham's portfolio, developer portfolio, developer, software developer, freelance developer, ML developer, GenAI developer, backend developer, AI developer",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="google-site-verification"
          content="Ssijj4aoUCOKQXAAVqy1hYbYZGlnjEehmCXB2fGV6zs"
        />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="bg-dark-gray text-light-gray">
        <CursorFollower />
        <SmoothCursor />
        <main className="flex-1 h-screen">{children}</main>
      </body>
    </html>
  );
}
