import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CursorFollower from "@/components/CursorFollower";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-dark-gray text-light-gray">
        <CursorFollower />
        <main className="flex-1 h-screen">{children}</main>
      </body>
    </html>
  );
}
