import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CursorFollower from "@/components/CursorFollower";
import { SmoothCursor } from "@/components/ui/smooth-cursor";
import ParticleField from "@/components/ParticleField";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Faham's Portfolio",
  description: "Generated by create next app",
  keywords:
    "iamfaham.me, faham portfolio, iamfaham, Syed Mohammed Faham, Faham's portfolio, developer portfolio, developer, software developer, freelance developer, ML developer, GenAI developer, backend developer, AI developer",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="google-site-verification"
          content="Ssijj4aoUCOKQXAAVqy1hYbYZGlnjEehmCXB2fGV6zs"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover"
        />
        <link rel="icon" href="/favicon-2.ico" />
      </head>
      <body className="bg-black text-light-gray">
        <ParticleField count={55} />
        <CursorFollower />
        <SmoothCursor />
        <main className="flex-1 h-screen">{children}</main>
      </body>
    </html>
  );
}
